on:
  push:
    branches:
      - master
    paths:
      - "package.json"

name: Create Release if version is bumped
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: git fetch --prune --unshallow --tags
      - uses: kanga333/config-value-exporter@main
        id: version
        with:
          key: version
          file: package.json
      - id: tag_check
        run: |
          git rev-parse v${{steps.version.outputs.result}} 2> /dev/null \
            || echo '::set-output name=exist::false'
      - name: Create Release
        if: steps.tag_check.outputs.exist == 'false'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.version.outputs.result}}
          release_name: Release v${{steps.version.outputs.result}}
          draft: false
          prerelease: false
